#!/bin/sh
#/etc/init.d/AlexService
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec forever --sourceDir=/home/pi/share/node -p /home/pi/share/node fauxmoServer.js  #scriptarguments
;;
stop)
exec forever stop --sourceDir=/home/pi/share/node fauxmoServer.js
;;
*)
echo "Usage: /etc/init.d/AlexaService {start|stop}"
exit 1
;;
esac
exit 0
